---
title: Publications and Presentations
---

## Publications

Barry, K.P., K.D. Mullin, K. Maze-Foley, L.A. Wilcox Talbot, P.E. Rosel, M.S. Soldevilla, L.A. Dias, M.R. Ramirez-Leon, and J.A. Litz. 2024. Killer whales in the Gulf of Mexico and North Atlantic off the Southeastern United States. Frontiers in Marine Science. [doi: 10.3389/fmars.2024.1360314](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2024.1460314/full)
<!-- (content\pubs\Barry et al. 2024.pdf) -->

Davis, G.E., M.F. Baumgartner, J.M. Bonnell, J. Bell, C. Berchok, J. Bort Thornton, S. Brault, G. Buchanan, R.A. Charif, D. Cholewiak, C.W. Clark, P. Corkeron, J. Delarue, K. Dudzinski, L. Hatch, J. Hildebrand, L. Hodge, H. Klinck, S. Kraus, B. Martin, D.K. Mellinger, H. Moors-Murphy, S. Nieukirk, D.P. Nowacek, S. Parks, A.J. Read, A.N. Rice, D. Risch, A. Sirovic, M. Soldevilla, K. Stafford, J.E. Stanistreet, E. Summers, S. Todd, A. Warde, and S.M. Van Parijs. 2017. Long-term passive acoustic recordings track the changing distribution of North Atlantic right whales (*Eubalaena glacialis*) from 2004 to 2014. Scientific Reports. [doi: 10.1038/s41598-017-13359-3](https://www.nature.com/articles/s41598-017-13359-3)
<!-- (content/pubs/Davis et al. 2017.pdf) -->

Davis, G.E., M.F. Baumgartner, P.J. Corkeron, J. Bell, C. Berchok, J.M. Bonnell, J. Bort Thornton, S. Brault, G.A. Buchanan, D.M. Cholewiak, C.W. Clark, J. Delarue, L.T. Hatch, H. Klinck, S.D. Kraus, B. Martin, D.K. Mellinger, H. Moors-Murphy, S. Nieukirk, D.P. Nowacek, S.E. Parks, D. Parry, N. Pegg, A.J. Read, A.N. Rice, D. Risch, A. Scott, M.S. Soldevilla, K.M. Stafford, J.E. Stanistreet, E. Summers, S. Todd, S.M. Van Parijs. 2020. Exploring movement patterns and changing distributions of baleen whales in the western North Atlantic using a decade of passive acoustic data. Global Change Biology. [doi: 10.1111/gcb.15191](https://onlinelibrary.wiley.com/doi/10.1111/gcb.15191)
<!-- (content/pubs/Davis et al. 2020.pdf) -->

Frasier, K.E., M.A. Roch, M.S. Soldevilla, S.M. Wiggins, L.P. Garrison, and J.A. Hildebrand. 2017. Automated classification of dolphin echolocation click types from the Gulf of Mexico. PLOS Computational Biology. [doi: 10.1371/journal.pcbi.1005823](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005823)
<!-- (content/pubs/Frasier et al. 2017.pdf) -->

Frasier, K.E., L.P. Garrison, M.S. Soldevilla, S.M. Wiggins, and J.A. Hildebrand. 2021. Cetacean distribution models based on visual and passive acoustic data. Scientific Reports. [doi: 10.1038/s41598-021-87577-1](https://www.nature.com/articles/s41598-021-87577-1)
<!-- (content/pubs/Frasier et al. 2021.pdf) -->

Garrison, L.P., M.S. Soldevilla, A. Martinez, and K.D. Mullin. 2024. A density surface model describing the habitat of the Critically Endangered Rice's whale *Balaenoptera ricei* in the Gulf of Mexico. Endangered Species Research. [doi: 10.3354/esr01324](https://www.int-res.com/articles/esr2024/54/n054p041.pdf)
<!-- (content/pubs/Garrison et al. 2024.pdf) -->

Haver, S.M., J. Gedamke, L.T. Hatch, R.P. Dziak, S. Van Parijs, M.F. McKenna, J. Barlow, C. Berchok, E. DiDonato, B. Hanson, J. Haxel, M. Holt, D. Lipski, H. Matsumoto, C. Meinig, D.K. Mellinger, S.E. Moore, E.M. Oleson, M.S. Soldevilla, and H. Klinck. 2018. Monitoring long-term soundscape trends in U.S. Waters: The NOAA/NPS Ocean Noise Reference Station Network. Marine Policy. [doi: 10..1016/j.marpol.2018.01.023](https://www.sciencedirect.com/science/article/pii/S0308597X17306309)
<!-- (content/pubs/Haver et al. 2018.pdf) -->

Kok, A.C.M., M.J. Hildebrand, M. MacArdle, A. Martinez, L.P. Garrison, M.S. Soldevilla, and J.A. Hildebrand. 2023. Kinematics and energetics of foraging behavior in Rice's whales of the Gulf of Mexico. Scientific Reports. [doi: 10.1038/s41598-023-35049-z](https://www.nature.com/articles/s41598-023-35049-z)
<!-- (content/pubs/Kok et al. 2023) -->

Lettrich, M.D., M.J. Asaro, D.L. Borggaard, D.M. Dick, R.B. Griffis, J.A. Litz, C.D. Orphanides, D.L. Palka, M.S. Soldevilla, B. Balmer, S. Chavez, D. Cholewiak, D. Claridge, R.Y. Ewing, K.L. Fazioli, D. Fertl, E.M. Fougeres, D. Gannon, L. Garrison, J. Gilbert, A. Gorgone, A. Hohn, S. Horstman, B. Josephson, R.D. Kenney, J.J. Kiszka, K. Maze-Foley, W. McFee, K.D. Mullin, K. Murray, D.E. Pendleton, J. Robbins, J.J. Roberts, G. Rodriguez-Ferrer, E.I. Ronje, P.E. Rosel, T. Speakman, J.E. Stanistreet, T. Stevens, M. Stolen, R. Tyson Moore, N.L. Vollmer, R. Wells, H.R. Whitehead, and A. Whitt. 2023. Vulnerability to climate change of United States marine mammal stocks in the western North Atlantic, Gulf of Mexico, and Caribbean. PLOS ONE. [doi: 10.1371/journal.pone.0290643](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0290643)
<!-- (content/pubs/Lettrich et al. 2023.pdf) -->

Rankin, S., T. Sakai, F.I. Archer, J. Barlow, D. Cholewiak, A.I. DeAngelis, J.L.K. McCullough, E.M. Oleson, A.E. Simonis, M.S. Soldevilla, and J.S. Trickey. 2024. Open-source machine learning BANTER acoustic classification of beaked whale echolocation pulses. Ecological Informatics. [doi: 10.1016/j.ecoinf.2024.10251](https://www.sciencedirect.com/science/article/pii/S1574954124000530)
<!-- (content/pubs/Rankin et al. 2024.pdf) -->

Rice, A.N., M.S. Soldevilla, and J.A. Quinlan. 2017. Nocturnal patterns in fish chorusing off the coasts of Georgia and eastern Florida. Bulletin of Marine Science. [doi: 10.5343/bms.2016.1043](content/pubs/Rice et al. 2017.pdf)

Roch, M.A., H. Batchelor, S. Baumann-Pickering, C.L. Berchok, D. Cholewiak, E. Fujioka, E.C. Garland, S. Herbert, J.A. Hildebrand, E.M. Oleson, S. Van Parijs, D. Risch, A. Sirovic, and M.S. Soldevilla. 2016. Management of acoustic metadata for bioacoustics. Ecological Informatics. [doi: 10.1016/j.ecoinf.2015.12.002](https://www.sciencedirect.com/science/article/pii/S1574954115001983)
<!-- (content/pubs/Roch et al. 2016.pdf) -->

Rosel, P.E., L. Engleby, L.P. Garrison, J.A. Litz, K.D. Mullin, M.S. Soldevilla, M. Srinivasan, L.A. Wilcox, T. Yamada, and B.J. Zoodsma. 2022. Response to Corkeron et al. "*Balaenoptera ricei* is also the Gulf of Mexico whale". Marine Mammal Science. doi: 10.1111.mms.12927
<!-- (content/pubs/Rosel et al. 2022.pdf) -->

Soldvilla, M.S., L.P. Garrison, E. Scott-Denton, and R.A. Hart. 2016. Estimated bycatch mortality of marine mammals in the Gulf of Mexico shrimp otter trawl fishery during 2012 to 2014. NOAA Technical Memorandum NMFS-SEFSC-697. [doi: 10.7289/V5/TM-SEFSC-697](https://repository.library.noaa.gov/view/noaa/12515)
<!-- (content/pubs/Soldevilla et al. 2016.pdf) -->

Soldevilla, M.S., J.A. Hildebrand, K.E. Frasier, L.A. Dias, A. Martinez, K.D. Mullin, P.E. Rosel, and L.P. Garrison. 2017. Spatial distribution and dive behavior of Gulf of Mexico Bryde's whales: potential risk of vessel strikes and fisheries interactions. Endangered Species Research. [doi: 10.3354/esr00834](https://www.int-res.com/articles/suppl/n032p533_supp.pdf)
<!-- (content/pubs/Soldevilla et al. 2017 ESR.pdf) -->

Soldevilla, M.S., K. Ternus, A. Cook, J.A. Hildebrand, K.E. Frasier, A. Martinez, and L.P. Garrison. 2022. Acoustic localization, validation, and characterization of Rice's whale calls. Journal of the Acoustical Society of America. 151(6). [doi:10.1121/10.0011677](https://pubs.aip.org/asa/jasa/article/151/6/4264/2839426/Acoustic-localization-validation-and)
<!-- (content/pubs/Soldevilla et al. 2022.pdf) -->

Soldevilla, M.S., A.N. Rice, C.W. Clark, and L.P. Garrison. 2014. Passive acoustic monitoring on the North Atlantic right whale calving grounds. Endangered Species Research. 25:115-140. [doi: 10.3354/esr00603](https://www.int-res.com/articles/esr2014/25/n025p115.pdf)
<!-- (content/pubs/Soldevilla et al. 2014.pdf) -->

Soldevilla, M.S., S. Baumann-Pickering, D. Cholewiak, L.E.W. Hodge, E.M. Oleson, and S. Rankin. 2017. Geographic variation in Risso's dolphin echolocation click spectra. Journal of the Acoustical Society of America. 142(2). [doi: 10.1121/1.4996002](https://pubs.aip.org/asa/jasa/article/142/2/599/640332/Geographic-variation-in-Risso-s-dolphin)
<!-- (content/pubs/Soldevilla et al. 2017 JASA.pdf) -->

Soldevilla, M.S., A.J. Debich, L.P. Garrison, J.A. Hildebrand, and S.M. Wiggins. 2022. Rice's whales in the northwestern Gulf of Mexico: call variation and occurrence beyond the known core habitat. Endangered Species Research. 48: 155-173. [doi: 10.3354/esr01196](https://www.int-res.com/articles/esr2022/48/n048p155.pdf)
<!-- (content/pubs/Soldevilla et al. 2022 ESR.pdf) -->

Soldevilla, M.S., A.J. Debich, I. Perez-Carballo, S. Jarriel, K.E. Frasier, L.P. Garrison, A. Gracia, J.A. Hildebrand, P.E. Rosel, and A. Serrano. 2024. Rice's whale occurrence in the western Gulf of Mexico from passive acoustic recordings. Marine Mammal Science. [doi: 10.1111/mms.13109](https://onlinelibrary.wiley.com/doi/10.1111/mms.13109)
<!-- (content/pubs/Soldevilla et al. 2024 MMS.pdf) -->

Solsona-Berga, A., K.E. Frasier, N. Posdaljian, S. Baumann-Pickering, S. Wiggins, M. Soldevilla, L. Garrison, and J.A. Hildebrand. 2024. Accounting for sperm whale population demographics in density estimation using passive acoustic monitoring. Marine Ecology Progress Series. 746: 121-140. [doi: 10.3354/meps14693](https://www.int-res.com/articles/meps_oa/m746p121.pdf)
<!-- (content/pubs/Solsona-Berga et al. 2024.pdf) -->


## Presentations


## News

[Rice's Whales Heard in the Western Gulf of Mexico](https://www.fisheries.noaa.gov/feature-story/rices-whales-heard-western-gulf-mexico)


## Blogs

[Collecting Information to Restore Marine Mammals and Seabirds in the Gulf of Mexico](https://www.fisheries.noaa.gov/taxonomy/term/1000381581)

[Deploying Passive Acoustic Recorders for North Atlantic Right Whale Calving Season](https://www.fisheries.noaa.gov/feature-story/deploying-passive-acoustic-recorders-north-atlantic-right-whale-calving-season)

Graduate students developed videos in [English](https://drive.google.com/file/d/1II6qgyNwlO3NdhiDYrZ4gS7hY8VIetEE/view) and [Spanish](https://drive.google.com/file/d/1E2A--zWOr8L_tKkAbOwFdWRmgsjm1iyq/view) describing the Gulf LISTEN HARP servicing cruises as part of the LISTEN GoMex project.

[In the Field: First hand accounts from researchers straight from the field](https://www.cetus.ucsd.edu/blog.html) (by Scripps Institution of Oceanography Researchers)


<!-- This is an optional page but is a great opportunity to highlight some of your publications and presentations. -->

<!-- SAEL example (add once this page is corrected) -->
